# Generated by Django 5.0.2 on 2024-02-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
