# Generated by Django 4.0 on 2024-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0004_remove_imageelement_image_imageelement_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageelement',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
